plugins {
    id 'com.android.application'
}

android {
    namespace 'com.joohkim.k5hudtest'
    compileSdk 36

    defaultConfig {
        applicationId 'com.joohkim.k5hudtest'
        minSdk 23
        targetSdk 36
        versionCode 6
        versionName '0.6-test'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.car.app:app:1.7.0'
    implementation 'androidx.car.app:app-projected:1.7.0'
}
